### ISSUE TITLE
压缩报错，图片未输出

### ISSUE THREAD

**Issue by lxn1445663013** [duking666/ImgCompressPlugin#1]
我的配置
![image](https://user-images.githubusercontent.com/23535332/56546450-279f2700-65ad-11e9-9287-0eba84127327.png)
错误日志如下
![image](https://user-images.githubusercontent.com/23535332/56546496-400f4180-65ad-11e9-98ef-b989f7b87ed8.png)

**Comment by KingKingDu** [comment]
已修复,请使用1.1.5版本

**Comment by lxn1445663013** [comment]
多谢




------------------ 原始邮件 ------------------
发件人: "KingKingDu"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 晚上8:07
收件人: "duking666/ImgCompressPlugin"<ImgCompressPlugin@noreply.github.com>;
抄送: "令水剑客"<1445663013@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [duking666/ImgCompressPlugin] 压缩报错，图片未输出 (#1)




已修复,请使用1.1.5版本

**Comment by lxn1445663013** [comment]
图片大于500K之后，输出文件正常，但是图片并没有被压缩，日志如下
![image](https://user-images.githubusercontent.com/23535332/56625903-f89eb900-6671-11e9-80a9-eab8473e7504.png)

**Comment by KingKingDu** [comment]
zopflipng是无损压缩,压缩率非常低,当压缩后的图片大小>原图时,日志会skip或者failed.主流项目中用tiny居多,建议尝试用tiny试一下效果会好一些.

**Comment by lxn1445663013** [comment]
是的，只有tinypng模式下才能压缩，其他的两种模式压缩均无效果，感谢解答
