### ISSUE TITLE
可以正常压缩,但是是否支持压缩指定目录下的图片???

### ISSUE THREAD

**Issue by lydlovezjr** [duking666/ImgCompressPlugin#2]
比如我只想压缩drawable下的,而不压缩mipmap里边的!

**Comment by KingKingDu** [comment]
暂时没对指定目录做白名单过滤,前请关注后续版本更新.如果mipmap中文件较少的,话,建议你暂时用白名单文件进行过滤防止被压缩.

**Comment by lydlovezjr** [comment]
期待!感谢.
