### ISSUE TITLE
不维护了？ 

### ISSUE THREAD

**Issue by ewgcat** [duking666/ImgCompressPlugin#6]
> Failed to apply plugin [id 'img-compressor']
   > Could not create task ':imgCompressTask'.
      > Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'imgCompressTask', but there is no existing task with that name.

androidstudio4.1.0和gradle6.5  classpath 'com.android.tools.build:gradle:4.1.0'

**Comment by i91h1r** [comment]
同问，6.5 不能用了

**Comment by KingKingDu** [comment]
#7 同个问题
请更新到 `classpath 'io.github.duking666:ImgCompressPlugin:1.2.1'` 以支持gradle.version >=6.0.
注意:域名从` com.kingkingdu.plugin`改为` io.github.duking666`. 同时注意仓库从`jcenter()` 迁移到 `mavenCentral()`
