### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by zhsl12** [duking666/ImgCompressPlugin#7]
A problem occurred evaluating root project 'xxxx'.
> Failed to apply plugin [id 'img-compressor']
   > Could not create task ':imgCompressTask'.
      > Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'imgCompressTask', but there is no existing task with that name.

 dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.kingkingdu.plugin:img-compressor:1.1.5'
    }

**Comment by KingKingDu** [comment]
please upgrade to `classpath 'io.github.duking666:ImgCompressPlugin:1.2.1' `,which support gradle.version >=6.0.

note: the host is from `com.kingkingdu.plugin` to `io.github.duking666`.And the repository is from `jcenter()` to `mavenCentral()`
